apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: miportfolio
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/Fabricio-Paragulla/Portfolio-Fabricio.git
    targetRevision: main
    path: deploy/miportfolio

  destination:
    server: https://kubernetes.default.svc
    namespace: miportfolio

  syncPolicy:
    automated:
      prune: true
      selfHeal: true