apiVersion: v1
kind: Secret
metadata:
  name: repo-secret-cred
  namespace: argocd
  labels: 
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/Fabricio-Paragulla/Portfolio-Fabricio.git
  username: Fabricio-Paragulla
  password: ${{ secrets.GITHUB_TOKEN }}