apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-deploy
  labels:
    app: portfolio-fabricio
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: portfolio-fabricio
  template:
    metadata:
      labels:
        app: portfolio-fabricio
    spec:
      containers:
      - name: portfolio-container
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 80
        # Inyectamos el ConfigMap como variables de entorno
        envFrom:
        - configMapRef:
            name: portfolio-config
      # Usamos el secreto de DockerHub (lo crearemos en el paso de despliegue)
      imagePullSecrets:
      - name: regcred