{{- if .Values.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
    name: ukiyo-api-gateway-config
    namespace: {{ .Release.namespace }}
data:
    NATS_SERVERS: {{ .Values.global.nats.url | quote }}
    REPO_GIT: {{ .Values.global.env.REPO_GIT | quote }}
    PORT: {{ .Values.global.env.PORT | quote }}
{{- end }}